const ORDER_STATUS = {
  PROCESSING: 'PROCESSING',
  SERVED: 'SERVED',
  NOT_PICKED_UP: 'NOT_PICKED_UP',
  PICKED_UP: 'PICKED_UP',
}

const ORDER_TYPE = {
  DINE_IN: 'DINE_IN',
  TAKE_AWAY: 'TAKE_AWAY',
}

const TIMESPAN = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
}

module.exports = {
  ORDER_STATUS,
  ORDER_TYPE,
  TIMESPAN,
};